### ISSUE TITLE
PHAR cannot be published due to an upstream issue

### ISSUE THREAD

**Issue by AlexSkrypnyk** [AlexSkrypnyk/scaffold#40]
https://github.com/reactphp/promise/issues/252

https://github.com/composer/composer/pull/11620

```bash
2023-09-09T06:24:03.9342445Z   - Installing humbug/box (4.3.8): Extracting archive
2023-09-09T06:24:04.0777833Z     Install of symfony/var-dumper failed
2023-09-09T06:24:04.1830005Z     Install of seld/jsonlint failed
2023-09-09T06:24:04.3146223Z     Install of justinrainbow/json-schema failed
2023-09-09T06:24:04.3229868Z     Install of humbug/php-scoper failed
2023-09-09T06:24:04.3329068Z     Skipped installation of bin bin/php-parse for package nikic/php-parser: name conflicts with an existing file
2023-09-09T06:24:04.5199032Z     Install of humbug/box failed
2023-09-09T06:24:04.5224281Z Unhandled promise rejection with ArgumentCountError: Too few arguments to function React\Promise\Promise::React\Promise\{closure}(), 0 passed in phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php on line 660 and exactly 1 expected in phar:///usr/bin/composer/vendor/react/promise/src/Promise.php:277
2023-09-09T06:24:04.5227758Z Stack trace:
2023-09-09T06:24:04.5228456Z #0 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(660): React\Promise\Promise::React\Promise\{closure}()
2023-09-09T06:24:04.5229368Z #1 phar:///usr/bin/composer/vendor/react/promise/src/Internal/FulfilledPromise.php(47): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
2023-09-09T06:24:04.5233862Z #2 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(661): React\Promise\Internal\FulfilledPromise->then()
2023-09-09T06:24:04.5252804Z #3 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(288): Composer\Installer\InstallationManager::Composer\Installer\{closure}()
2023-09-09T06:24:04.5253920Z #4 phar:///usr/bin/composer/vendor/react/promise/src/Promise.php(37): React\Promise\Promise->call()
2023-09-09T06:24:04.5254734Z #5 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(663): React\Promise\Promise->__construct()
2023-09-09T06:24:04.5255617Z #6 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(221): Composer\Installer\InstallationManager->runCleanup()
2023-09-09T06:24:04.5256466Z #7 phar:///usr/bin/composer/src/Composer/Installer.php(791): Composer\Installer\InstallationManager->execute()
2023-09-09T06:24:04.5257175Z #8 phar:///usr/bin/composer/src/Composer/Installer.php(616): Composer\Installer->doInstall()
2023-09-09T06:24:04.5257866Z #9 phar:///usr/bin/composer/src/Composer/Installer.php(290): Composer\Installer->doUpdate()
2023-09-09T06:24:04.5258585Z #10 phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php(490): Composer\Installer->run()
2023-09-09T06:24:04.5259366Z #11 phar:///usr/bin/composer/src/Composer/Command/RequireCommand.php(339): Composer\Command\RequireCommand->doUpdate()
2023-09-09T06:24:04.5260178Z #12 
```

**Comment by AlexSkrypnyk** [comment]
Waiting for Composer 2.6.3 release

**Comment by AlexSkrypnyk** [comment]
composer 2.6.3 was released

This build, however, failed
https://github.com/AlexSkrypnyk/scaffold/actions/runs/6196672077/job/16823789690

Need to wait for a day and re-try.

**Comment by AlexSkrypnyk** [comment]
This was related to using incorrect action runner where the release ran on the runner, but the PHP version was installed into the docker container.
